# Reader and Writer

protocol-id: "lEdge" 

zmq-endpoint-raw-block: "tcp://0.0.0.0:28332" 
zmq-endpoint-hash-block: "tcp://0.0.0.0:28334"

# Writer Only  -----
enable-writer: false # run writer service

write-interval-blocks: 1 # Configure write op. frequency

layer-edge-rpc:
  http: "https://testnet-rpc.layeredge.io/" 
  wss: "wss://testnet-rpc.layeredge.io/"

private-key:
  internal: "get-from-env" # PRIVATE_KEY_INTERNAL
  signer: "get-from-env" # PRIVATE_KEY_SIGNER

relayer:
  host: "localhost:18443" 
  user: "rishabh"
  pass: "LT8qjx7hkw4pPYosLEI40qAMuEICD4-TGnG6mPMnMIw" 

bitcoin-cli-path: "/home/rishabh/bitcoin-cli/bitcoin-27.0/bin/bitcoin-cli"
bash-script-path: "/home/rishabh/bitcoin-da-main/scripts/"
