# Reader and Writer

protocol-id: "lEdge" 

zmq-endpoint: "tcp://127.0.0.1:28332" # "13.60.51.28"

# Writer Only  -----
enable-writer: false # run writer service

write-interval-blocks: 10 # configure write op. frequency

layer-edge-rpc:
  http: "https://testnet-rpc.layeredge.io/" 
  wss: "wss://testnet-rpc.layeredge.io/"

private-key:
  internal: "get-from-env" # PRIVATE_KEY_INTERNAL
  signer: "get-from-env" # PRIVATE_KEY_SIGNER

relayer:
  host: "localhost:18443" 
  user: "jeet" 
  pass: "SzKyQMucjU9pd6om64xcuMiEp4FqDtKAn_Q6QA16e6k" 
