
# the following config can be overridden by environment variables
# env name defined after "#"

protocol-id: "layer-edge" # PROTOCOL_ID

layer-edge-rpc:
  http: "https://testnet-rpc.layeredge.io/http" 
  wss: "wss://testnet-rpc.layeredge.io/ws"

private-key:
  internal: "cNR4CfUPBZNEZE9rShP4ix2NRPUNFfmDjecG7W9ySpupjGTMUKbw" # PRIVATE_KEY_INTERNAL
  signer: "get-from-env" # PRIVATE_KEY_SIGNER

relayer:
  host: "localhost:18443" # RELAYER_HOST
  user: "jeet" # RELAYER_USER 
  pass: "SzKyQMucjU9pd6om64xcuMiEp4FqDtKAn_Q6QA16e6k" # RELAYER_PASS
