
# the following config can be overridden by environment variables
# env name defined after "#"

protocol-id: "layer-edge" # PROTOCOL_ID

layer-edge-rpc:
  http: "https://testnet-rpc.layeredge.io/http" 
  wss: "wss://testnet-rpc.layeredge.io/ws"

private-key:
  internal: "get-from-env" # PRIVATE_KEY_INTERNAL
  signer: "get-from-env" # PRIVATE_KEY_SIGNER

wallet-relayer:
  host: "localhost:18332" # WALLET_RELAYER_HOST
  user: "jeet" # WALLET_RELAYER_USER 
  pass: "CvfIUhldPYHVVrdLzbRXQ6PKKcg=" # WALLET_RELAYER_PASS

ws-relayer:
  host: "localhost:18334" # WS_RELAYER_HOST
  user: "jeet" # WS_RELAYER_USER 
  pass: "CvfIUhldPYHVVrdLzbRXQ6PKKcg=" # WS_RELAYER_PASS
